### ISSUE TITLE
Morphological Chart

### ISSUE THREAD

**Issue by PrashanthJain** [PrashanthJain/inverted-pendulum#10]
Come up with a Morphological Chart considering all the functions and sub-functions in the system.

**Comment by vmnagda** [comment]
motion transmission Mechanism 
Actuator
Power source
materials for pendulum link
feedback unit 
platform material 
energy converter 
storage energy
amplification signal
microprocessor
controller
communication means /protocol
control system 
programming language
user interface

**Comment by vmnagda** [comment]
motion transmission mechanism:
linear motion 
shaft
lead screw
ball screw

**Comment by amitjambure** [comment]
Solar Energy. ...
Wind Energy. ...
Geothermal Energy. ...
Hydrogen Energy. ...
Tidal Energy. ...
Wave Energy. ...
Hydroelectric Energy. ...
Biomass Energy.

**Comment by amitjambure** [comment]
power source

**Comment by PrashanthJain** [comment]
In Morphological Chart,
Channeling
Signal Input

**Comment by vmnagda** [comment]
actuator:
dc motor
stepper motors
peizo electric actuators
pnewmatically  driven actuator

**Comment by amitjambure** [comment]
different types programming language
C++
Data structure
HTML
Python
Arm
PHP
Arduino
XML
Java
C#

**Comment by AishwaryaMahavarkar** [comment]
actuator-
1. induction motor 
2. stepper motor
3. dc motor
4. permanent magnet motor

**Comment by AishwaryaMahavarkar** [comment]
feedback unit
1. encoder
2. sensor
3. potentiometer
4. tachometer
5. resolver

**Comment by amitjambure** [comment]
Storage Energy

Electrical

-Capacitor
-Superconducting magnetic energy  storage(SMES)

Electro chemical 

-Flow Battery
-Rechargeable Battery
-Super Capacitor
-Ultra Battery

**Comment by Abhillubillu** [comment]
Material for pendulum
-alluminium
-nylon
-copper
-steel 
-fibre
-plastic

**Comment by AishwaryaMahavarkar** [comment]
controller
 

1. PLC
2.  Rasberry pi
3.  PID

**Comment by vmnagda** [comment]
energy converter:
rectifier
voltage regulator
inverter
transformer
mains power supply unit

**Comment by Abhillubillu** [comment]
User Interface
-command line.
-graphical user interface (GUI)
-menu driven.
-form based.
-natural language.

**Comment by Abhillubillu** [comment]
Channeling signal
-Digital (discrete) or analog (continuous) channel
-Transmission medium, for example a fibre channel
-Multiplexed channel
-Computer network virtual channel
-Simplex communication, duplex communication or half duplex communication channel
-Return channel
-Uplink or downlink (upstream or downstream channel)
-Broadcast channel, unicast channel or multicast channel

**Comment by AishwaryaMahavarkar** [comment]
microprocessors

1. CISC-Complex Instruction Set Microprocessors
2. 8086 mciroprocessors
3. RISC-Reduced Instruction Set Microprocessor
4. ASIC- Application Specific Integrated Circuit
5. DSP's-Digital Signal Microprocessors.

**Comment by vmnagda** [comment]
controller

arduino mega 
raspberry pie
beagle board
pic
ARM

**Comment by AishwaryaMahavarkar** [comment]
microprocessors

1. CISC-Complex Instruction Set Microprocessors
2. 8086 mciroprocessors
3. RISC-Reduced Instruction Set Microprocessor
4. ASIC- Application Specific Integrated Circuit
5. DSP's-Digital Signal Microprocessors.
