### ISSUE TITLE
Detailed Function Structure

### ISSUE THREAD

**Issue by PrashanthJain** [PrashanthJain/inverted-pendulum#11]
Come up with a Detailed Function Structure wherein functions are divided into numerous sub-functions and modules.

**Comment by vmnagda** [comment]
under process instruction we can sub functions 
input the instruction 
evaluate the set of instuction 
execute each instructions of the set parallely

**Comment by vmnagda** [comment]
under signal conversion the sub function we can add is 
accept the signal 
convert the signal to a instuctions 
combine all the instructions into a set of instructions

**Comment by vmnagda** [comment]
signal conversion 2.
input/accept the set of instructions 
convert the signal according to requirements .
take the output of the converted signal

**Comment by vmnagda** [comment]
accept energy .
plug to the mains 
turn on the energy

**Comment by vmnagda** [comment]
for deployment of kinematics 

obtain postion feedback of the unstable pendulum
intiate the actuator
accept the instruction 
control of the pendulum

**Comment by AishwaryaMahavarkar** [comment]
Stabilizing /Balancing of the system:
- Swing Motion of pendulum
- Inversion of the pendulum
- Linearization of the pendulum

Accept the energy:
- i/p into the converter
-energy conversion
-o/p converted energy
-store converted energy

**Comment by AishwaryaMahavarkar** [comment]
Convert energy
- i/p energy into converter
- energy conversion 
- o/p converted energy
- store converted energy

**Comment by AishwaryaMahavarkar** [comment]
store energy
- i/p processed energy into energy storing device
- energy storing 
- o/p stored energy

**Comment by AishwaryaMahavarkar** [comment]
Channelise the energy
- stored energy distribution
- supply of required amount energy

**Comment by AishwaryaMahavarkar** [comment]
Feedback unit
- i/p  sensor's o/p 
- distribution of sensor o/p

**Comment by AishwaryaMahavarkar** [comment]
Accept control instruction
- power i/p
- accept user i/p instruction
- store user instruction

**Comment by AishwaryaMahavarkar** [comment]
Store instruction

- i/p instructions to system
- store instructions into memory

**Comment by AishwaryaMahavarkar** [comment]
Signal conversion
- i/p user instructions to converter
- signal conversion in required form
- store converted signal

**Comment by AishwaryaMahavarkar** [comment]
Process instruction
- i/p converted signal to the system
- system interprets the signal
- processing of signal
- o/p processed signal

store processed signal
- i/p processed signal 
- storing of signal
- o/p stored signal
